import type { RepositorySignal } from "./city-model";

type DemoSeed = Partial<RepositorySignal> &
  Pick<
    RepositorySignal,
    | "name"
    | "description"
    | "language"
    | "stars"
    | "commits30d"
    | "contributorCount"
  >;

const seeds: DemoSeed[] = [
  {
    name: "atlas-engine",
    description: "Real-time spatial engine for connected urban systems.",
    language: "Rust",
    stars: 18420,
    commits30d: 286,
    contributorCount: 164,
    mergedPullRequests30d: 48,
    closedIssues30d: 31,
    openedIssues30d: 22,
    sizeKb: 186000,
  },
  {
    name: "prism-ui",
    description: "An expressive design system for complex data products.",
    language: "TypeScript",
    stars: 12680,
    commits30d: 212,
    contributorCount: 119,
    mergedPullRequests30d: 37,
    closedIssues30d: 28,
    openedIssues30d: 18,
    sizeKb: 94000,
  },
  {
    name: "signal-grid",
    description: "Streaming event infrastructure with a tiny operational footprint.",
    language: "Go",
    stars: 8930,
    commits30d: 174,
    contributorCount: 76,
    mergedPullRequests30d: 29,
    closedIssues30d: 18,
    openedIssues30d: 15,
    sizeKb: 118000,
  },
  {
    name: "lumen",
    description: "GPU-accelerated analytical visualization primitives.",
    language: "TypeScript",
    stars: 7420,
    commits30d: 151,
    contributorCount: 62,
    mergedPullRequests30d: 22,
    closedIssues30d: 14,
    openedIssues30d: 11,
    sizeKb: 72000,
  },
  {
    name: "vector-search",
    description: "Distributed semantic retrieval for high-dimensional datasets.",
    language: "Python",
    stars: 6940,
    commits30d: 128,
    contributorCount: 88,
    mergedPullRequests30d: 18,
    closedIssues30d: 26,
    openedIssues30d: 17,
    sizeKb: 132000,
  },
  {
    name: "pulse-api",
    description: "Low-latency edge API for telemetry and health signals.",
    language: "Go",
    stars: 4810,
    commits30d: 117,
    contributorCount: 51,
    mergedPullRequests30d: 20,
    closedIssues30d: 13,
    openedIssues30d: 9,
    sizeKb: 68000,
  },
  {
    name: "neural-blocks",
    description: "Composable building blocks for practical machine learning.",
    language: "Python",
    stars: 11320,
    commits30d: 96,
    contributorCount: 104,
    mergedPullRequests30d: 15,
    closedIssues30d: 19,
    openedIssues30d: 21,
    sizeKb: 154000,
  },
  {
    name: "orbit-cli",
    description: "One command to manage every service in your workspace.",
    language: "Rust",
    stars: 3150,
    commits30d: 84,
    contributorCount: 44,
    mergedPullRequests30d: 14,
    closedIssues30d: 8,
    openedIssues30d: 7,
    sizeKb: 46000,
  },
  {
    name: "ember-cache",
    description: "Predictable caching for reactive applications.",
    language: "TypeScript",
    stars: 2640,
    commits30d: 73,
    contributorCount: 38,
    mergedPullRequests30d: 12,
    closedIssues30d: 11,
    openedIssues30d: 5,
    sizeKb: 34000,
  },
  {
    name: "canopy",
    description: "Secure service orchestration for multicloud environments.",
    language: "Java",
    stars: 2240,
    commits30d: 63,
    contributorCount: 36,
    mergedPullRequests30d: 10,
    closedIssues30d: 7,
    openedIssues30d: 8,
    sizeKb: 91000,
  },
  {
    name: "echo-docs",
    description: "Documentation that stays synchronized with your code.",
    language: "TypeScript",
    stars: 1950,
    commits30d: 54,
    contributorCount: 31,
    mergedPullRequests30d: 9,
    closedIssues30d: 6,
    openedIssues30d: 4,
    sizeKb: 28000,
  },
  {
    name: "flux-worker",
    description: "Durable background jobs for edge-native applications.",
    language: "JavaScript",
    stars: 1780,
    commits30d: 48,
    contributorCount: 28,
    mergedPullRequests30d: 8,
    closedIssues30d: 5,
    openedIssues30d: 6,
    sizeKb: 24000,
  },
  {
    name: "harbor-auth",
    description: "Identity primitives designed for developer-first products.",
    language: "Kotlin",
    stars: 1420,
    commits30d: 41,
    contributorCount: 24,
    mergedPullRequests30d: 7,
    closedIssues30d: 8,
    openedIssues30d: 4,
    sizeKb: 58000,
  },
  {
    name: "drift-mobile",
    description: "Offline-first data synchronization for mobile teams.",
    language: "Swift",
    stars: 1230,
    commits30d: 35,
    contributorCount: 21,
    mergedPullRequests30d: 6,
    closedIssues30d: 4,
    openedIssues30d: 3,
    sizeKb: 44000,
  },
  {
    name: "quartz",
    description: "Minimal state machines for ambitious interfaces.",
    language: "TypeScript",
    stars: 980,
    commits30d: 27,
    contributorCount: 17,
    mergedPullRequests30d: 5,
    closedIssues30d: 3,
    openedIssues30d: 2,
    sizeKb: 18000,
  },
  {
    name: "relay-labs",
    description: "Experiments in real-time collaboration infrastructure.",
    language: "Elixir",
    stars: 760,
    commits30d: 19,
    contributorCount: 14,
    mergedPullRequests30d: 3,
    closedIssues30d: 3,
    openedIssues30d: 4,
    sizeKb: 32000,
  },
  {
    name: "sonar",
    description: "Small observability probes with clear operational signals.",
    language: "Go",
    stars: 640,
    commits30d: 15,
    contributorCount: 12,
    mergedPullRequests30d: 3,
    closedIssues30d: 2,
    openedIssues30d: 1,
    sizeKb: 12000,
  },
  {
    name: "foundry",
    description: "A dependable toolbox for repository automation.",
    language: "Python",
    stars: 510,
    commits30d: 9,
    contributorCount: 9,
    mergedPullRequests30d: 2,
    closedIssues30d: 2,
    openedIssues30d: 1,
    sizeKb: 17000,
  },
  {
    name: "legacy-console",
    description: "The original operations console, preserved for reference.",
    language: "JavaScript",
    stars: 3840,
    commits30d: 0,
    contributorCount: 46,
    archived: true,
    sizeKb: 86000,
    pushedAt: "2024-03-12T08:00:00Z",
  },
  {
    name: "tiny-metrics",
    description: "A focused metrics utility with no runtime dependencies.",
    language: "TypeScript",
    stars: 340,
    commits30d: 4,
    contributorCount: 6,
    mergedPullRequests30d: 1,
    sizeKb: 4200,
  },
];

export const demoRepositories: RepositorySignal[] = seeds.map((seed, index) => ({
  id: `demo-${index + 1}`,
  name: seed.name,
  fullName: `open-city-labs/${seed.name}`,
  description: seed.description,
  url: `https://github.com/open-city-labs/${seed.name}`,
  language: seed.language,
  stars: seed.stars,
  forks: seed.forks ?? Math.max(2, Math.round(seed.stars * 0.08)),
  openIssues: seed.openIssues ?? Math.max(0, Math.round(seed.commits30d * 0.09)),
  sizeKb: seed.sizeKb ?? 26000,
  createdAt: seed.createdAt ?? `202${index % 5}-02-14T10:00:00Z`,
  pushedAt:
    seed.pushedAt ??
    `2026-07-${String(Math.max(3, 26 - index)).padStart(2, "0")}T18:20:00Z`,
  archived: seed.archived ?? false,
  isFork: seed.isFork ?? false,
  commits30d: seed.commits30d,
  mergedPullRequests30d: seed.mergedPullRequests30d ?? 0,
  closedIssues30d: seed.closedIssues30d ?? 0,
  openedIssues30d: seed.openedIssues30d ?? 0,
  contributorCount: seed.contributorCount,
  metricsEstimated: false,
}));

// The demo is an immutable, build-cached snapshot and never requires GitHub.
demoRepositories.forEach(Object.freeze);
Object.freeze(demoRepositories);
